ci: install stable FreeCAD from PPA
the version in the official repository is 0.16. Ubuntu, it's 2020.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,7 +5,10 @@ on:
   - push
 jobs:
   build:
-    runs-on: ubuntu-latest
+    # XXX use 20.04 for python3. should be replaced with ubuntu-latest when
+    # 20.04 becomes the default.
+    # https://github.com/actions/virtual-environments/issues/1816
+    runs-on: ubuntu-20.04
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -14,10 +17,22 @@ jobs:
 
       - name: Install dependencies
         run: |
+          sudo add-apt-repository ppa:freecad-maintainers/freecad-stable
           sudo apt-get update
-          sudo apt-get install -y freecad freebsd-buildutils
+          sudo apt-get install -y freecad freecad-python3 freebsd-buildutils
 
       - name: Build STL files
         run: |
-          fmake PYTHONPATH=/usr/lib/freecad/lib
-          ls *.stl
+
+          # XXX fixup python module path
+          # https://forum.freecadweb.org/viewtopic.php?t=37099
+          for D in Mod Ext Gui; do
+            (cd /usr/lib/freecad-python3 && sudo ln -s /usr/share/freecad/${D} ${D})
+          done
+          fmake PYTHONPATH=/usr/lib/freecad/lib 2>&1 | tee build.log
+
+          # XXX FreeCAD exits with zero even when failed to load modules
+          if grep -i error build.log; then
+            exit 1
+          fi
+          ls -al *.stl
